### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by poudink** [smellymoo/moojelly#5]
I notice you haven't yet chosen a license for this. From what I understand, unlicensed code defaults to exclusive rights. In other words, you are the only person who is currently legally allowed to distribute and modify your code. If this was deliberate, you can ignore this issue. If it wasn't, please include a license.

**Comment by smellymoo** [comment]
OK will do.

**Comment by smellymoo** [comment]
Where do I set a license?

**Comment by smellymoo** [comment]
Done
